name: CI

on:
  # Trigger the workflow on push to the master branch
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      env:
        TEMP_CLONE_FOLDER: dsp-devops-wiki
        ACTION_NAME: rhiananthony
        ACTION_EMAIL: rhian.anthony@gmail.com
        WIKI_PUSH_MESSAGE: "Pushing latest changes to master branch"
      run: |
        echo "current path: $(pwd)"
        
        echo "Configuring Github"
        git config user.name $ACTION_NAME
        git config user.email $ACTION_EMAIL
        git clone https://github.com/broadinstitute/dsp-devops-wiki.git
        cd $TEMP_CLONE_FOLDER
        echo "current path: $(pwd)"
        ls
        
        # echo "Configuring Github again"
        git config user.name $ACTION_NAME
        git config user.email $ACTION_EMAIL
        
        echo "setting upstream branch"
        git push -u https://github.com/broadinstitute/dsp-devops-wiki.wiki.git master
        
        # echo "Adding files"
        # git add .
        
        # echo "Committing files"
        # git commit -m "$WIKI_PUSH_MESSAGE"
        
        
        # echo "Pushing to the wiki master branch"
        # git push -f origin master
