name: CI

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Publish master branch of repo to wiki
      env:
        TEMP_CLONE_FOLDER: "dsp-devops-wiki"
        ACTION_NAME: rhiananthony
        ACTION_EMAIL: rhian.anthony@gmail.com
        WIKI_PUSH_MESSAGE: "Pushing latest changes to master branch"
      run: |
        pwd
        echo "setting upstream branch"
        git push -f --set-upstream https://${{ secrets.GH_PAT }}@github.com/broadinstitute/${TEMP_CLONE_FOLDER}.wiki.git master

        # echo "Committing files"
        # git commit -m "$WIKI_PUSH_MESSAGE"

        # echo "Pushing to the wiki master branch"
        # git push -f origin master
