name: CI

on:
  # Trigger the workflow on push to the master branch
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      env:
        TEMP_CLONE_FOLDER: dsp-devops-wiki
        ACTION_NAME: rhiananthony
        ACTION_EMAIL: rhian.anthony@gmail.com
        WIKI_PUSH_MESSAGE: "Pushing latest changes to master branch"
      run: |
        mkdir $TEMP_CLONE_FOLDER
        cd $TEMP_CLONE_FOLDER
        git init
        git config user.name $ACTION_NAME
        git config user.email $ACTION_EMAIL
        git clone https://github.com/broadinstitute/dsp-devops-wiki.git
        echo "PATH: $(pwd)"
        cd $TEMP_CLONE_FOLDER
        ls
        
        echo "Pushing new pages"
        git config user.name $ACTION_NAME
        git config user.email $ACTION_EMAIL
        git add .
        git commit -m "$WIKI_PUSH_MESSAGE"
        git push -f --set-upstream https://github.com/broadinstitute/dsp-devops-wiki.wiki.git
