name: CI

on:
  # Trigger the workflow on push to the master branch
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      env:
        TEMP_CLONE_FOLDER: dsp-devops-wiki
        
      run: |
        cd ..
        echo "TEMP_CLONE_FOLDER: ${TEMP_CLONE_FOLDER}"
        git pull "https://github.com/broadinstitute/${TEMP_CLONE_FOLDER}.git"
        echo "Pushing new pages"
        cd $TEMP_CLONE_FOLDER
        ls
        git add .
        git status
        # git commit -m "$WIKI_PUSH_MESSAGE"
        
        # echo "Pushing new pages"
        # cd $TEMP_CLONE_FOLDER
        # git add .
        # git commit -m "$WIKI_PUSH_MESSAGE"
        # git push --set-upstream https://${GH_PAT}@github.com:$OWNER/$REPO_NAME.wiki.git master
        
