name: CI

on:
  # Trigger the workflow on push to the master branch
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      env:
        TEMP_CLONE_FOLDER: "dsp-devops-wiki"
        ACTION_NAME: rhiananthony
        ACTION_EMAIL: rhian.anthony@gmail.com
        WIKI_PUSH_MESSAGE: "Pushing latest changes to master branch"
        GH_PAT: "fe49eba74cf8565da4348b1bd2403f12a2da14f4"
      run: |
        echo "current path: $(pwd)"
        
        echo "Configuring Github"
        mkdir ${TEMP_CLONE_FOLDER}
        cd ${TEMP_CLONE_FOLDER}
        git init
        git config user.name ${ACTION_NAME}
        git config user.email ${ACTION_EMAIL}
        
        echo "Pulling repo"
        git pull https://${GH_PAT}@github.com/broadinstitute/dsp-devops-wiki.git
        echo "current path: $(pwd)"
        ls
        
        echo "setting upstream branch"
        echo "Token: ${GH_PAT}"
        git push --set-upstream https://${GH_PAT}@github.com/broadinstitute/${TEMP_CLONE_FOLDER}.wiki.git master
        
        # echo "Committing files"
        # git commit -m "$WIKI_PUSH_MESSAGE"
        
        # echo "Pushing to the wiki master branch"
        # git push -f origin master
