name: CI

on:
  # Trigger the workflow on push to the master branch
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Publish master branch of repo to wiki
      env:
        TEMP_CLONE_FOLDER: "dsp-devops-wiki"
        ACTION_NAME: rhiananthony
        ACTION_EMAIL: rhian.anthony@gmail.com
        WIKI_PUSH_MESSAGE: "Pushing latest changes to master branch"
      run: |
        # clone repo with personal token
        echo "Configuring Github"
        mkdir ${TEMP_CLONE_FOLDER}
        cd ${TEMP_CLONE_FOLDER}
        git init
        git config user.name ${ACTION_NAME}
        git config user.email ${ACTION_EMAIL}

        # pull repo
        echo "Pulling repo"
        git pull https://${{ secrets.GH_PAT }}@github.com/broadinstitute/dsp-devops-wiki.git

        # delete home.md
        rm -f Home.md

        # run render Home.md script
        echo "rending Home.md"
        sh render_home.sh

        echo "setting upstream branch"
        #change to push to wiki.wiki
        git add Home.md
        git commit -m "Updated Home.md `date +'%Y-%m-%d %H:%M:%S'`"
        gitstatus=$(git status -sb)
        if echo "$gitstatus" | grep "ahead";
        then
          git push -f -v --set-upstream https://${{ secrets.GH_PAT }}@github.com/broadinstitute/${TEMP_CLONE_FOLDER}.wiki.git master
        else
          echo $status
        fi
